/**
 *
 */
package by.bsu.veget.data;

import by.bsu.veget.enums.VegetEnum;
import by.bsu.veget.enums.VegetMethodOfPreparationEnum;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.Map;

/**
 *    Please don`t check this class as task, i wrote it for the more comfortable init;
 *
 *
 */
public class VegetReceptJFrame extends javax.swing.JFrame {
    public static final String RECIPE_BIN = "recipe.";
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    // private JFileChooser fileChooser = null;
    private final Map<VegetEnum, String> salat = new HashMap<>();

    /**
     * Creates new form vegetReceptJFrame
     */
    public VegetReceptJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        JButton jButton1 = new JButton();
        jButton2 = new javax.swing.JButton();
        JTextField jTextField1 = new JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        JButton jButton3 = new JButton();
        jTextField2 = new javax.swing.JTextField();
        JButton jButton4 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            /**
             *
             */
            private static final long serialVersionUID = 1L;

            /**
             *
             */

            public int getSize() {
                System.out.println(salat.size());
                return salat.keySet().size();

            }

            public Object getElementAt(int i) {
                // Object obj = salat.keySet().toArray()[0];
                // System.out.println(obj+"= oblject");
                // return salat.get(salat.keySet().toArray()[i]);
                synchronized (salat) {
                    return salat.keySet().toArray(new String[salat.keySet().size()])[i];
                }
            }
        });
        jScrollPane1.setViewportView(jList1);
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jList1.repaint();
        jButton1.setText("Add ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }

        });
        jButton2.setEnabled(false);
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("Recipe Name");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(VegetEnum
                .values()));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                VegetMethodOfPreparationEnum.values()));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent event) {

                saveToGraphicsFile(new File(RECIPE_BIN));

            }

        });

        jTextField2.setText("Params");
        jTextField2.setEnabled(false);

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegetReceptJFrame.this.setVisible(false);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(
                                                                                        jTextField2,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        jComboBox1,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18,
                                                                                                        18,
                                                                                                        18)
                                                                                                .addComponent(
                                                                                                        jComboBox2,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(
                                                                                        jTextField1,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addGap(18, 18,
                                                                        18)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(
                                                                                        jButton1,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(
                                                                                        jButton2,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(24, 24,
                                                                        24)
                                                                .addComponent(
                                                                        jButton3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        jButton4)))
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        127,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        188,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        jTextField1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        37,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(
                                                                                                                        jComboBox1,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(
                                                                                                                        jComboBox2,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(21,
                                                                                                        21,
                                                                                                        21)
                                                                                                .addComponent(
                                                                                                        jTextField2,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        35,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        jButton1)
                                                                                                .addGap(18,
                                                                                                        18,
                                                                                                        18)
                                                                                                .addComponent(
                                                                                                        jButton2)))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        47,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jButton3)
                                                                                .addComponent(
                                                                                        jButton4))))
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // if (jComboBox1.getSelectedItem().equals(
        // VegetMethodOfPreparationEnum.CHOOSE)) {
        // jTextField2.setEnabled(true);
        // } else
        jTextField2.setEnabled(false);
    }

    private void jButton1ActionPerformed(ActionEvent evt) {
        String vg;
        if (salat.containsKey(jComboBox2.getSelectedItem())) {
            String other = salat.get(jComboBox2.getSelectedItem()) + "/";
            // System.out.println(other);

            vg = other + jComboBox1.getSelectedItem().toString();
        } else
            vg = jComboBox1.getSelectedItem().toString();
        /*
           * if (jComboBox1.getSelectedItem().equals(
           * VegetMethodOfPreparationEnum.CHOOSE)) { vg =vg+jTextField2.getText();
           * }
           */
        salat.put((VegetEnum) jComboBox2.getSelectedItem(), vg);
        System.out.println(salat.toString());
        jList1.repaint();
        jScrollPane1.repaint();
        this.repaint();
        jButton2.setEnabled(true);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        jList1.remove(jList1.getSelectedIndex());
        jList1.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VegetReceptJFrame().setVisible(true);
            }
        });
    }

    private javax.swing.JButton jButton2;
    private JComboBox<VegetMethodOfPreparationEnum> jComboBox1;
    private JComboBox<VegetEnum> jComboBox2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;

    // End of variables declaration
    private void saveToGraphicsFile(File selectedFile) {
        try {
            // ������� ����� �������� ����� ������, ������������ � ���������
            // ����
            // DataOutputStream out = new DataOutputStream(new FileOutputStream(
            // selectedFile));
            PrintStream out = new PrintStream(selectedFile);
            // �������� � ����� ������ ������� �������� X � �����, ��������
            // ���������� � �����
            // Double sum = -1.0;

            Object[] obj = salat.keySet().toArray();
            for (Object i : obj) {
                salat.get(i);
                out.print(i.toString() + "/");
                out.println(salat.get(i));
                // out.writeUTF("\n");

                /*
                     * out.writeDouble((Double) data.getValueAt(i, 0) - 0.025);
                     * out.writeDouble((0)); out.writeDouble((Double)
                     * data.getValueAt(i, 0)); sum = sum * (-0.8);
                     * out.writeDouble((sum)); out.writeDouble((Double)
                     * data.getValueAt(i, 0) + 0.025); out.writeDouble((sum + 0.1));
                     * out.writeDouble((Double) data.getValueAt(i, 0) + 0.025);
                     * out.writeDouble((sum + 0.1)); out.writeDouble((Double)
                     * data.getValueAt(i, 0) + 0.025); out.writeDouble((0));
                     */
            }
            // ������� ����� ������
            out.close();
        } catch (Exception e) {
            // �������������� �������� "������������" � ������ ������ ����� ��
            // ������������,
            // ��� ��� �� ���� �����?�, � �� ��������� ��� ������
        }
    }

}
